CREATE TABLE TEST_FLY(
  APP_USER_UUID NUMERIC,
  USER_NAME VARCHAR(25) NOT NULL,
  ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
  CREDENTIAL TEXT NOT NULL,
  CREATED_DATE DATE NOT NULL DEFAULT now(),
  CREATED_BY VARCHAR(50)
);
